### ISSUE TITLE
Can HDF5Matrix and RLEMatrix work together?

### ISSUE THREAD

**Issue by phaverty** [Bioconductor/HDF5Array#12]
It would be cool to be able to persist an RLEMatrix in HDF5 (in compressed form). I don't know if you'd want to read from the HDF5 lazily or just all at once, given the small size. I'm thinking of the case where you have an SE with lots of matrices (RLE and dense) and you want them persisted all together.

**Comment by lawremi** [comment]
One option would be a delayed implementation of Rle, another would be a direct implementation as a new DelayedArray backend.

**Comment by LTLA** [comment]
@phaverty I assume you're referring to storage of the runs and lengths as HDF5 `DataSet`s of their own? This is a similar idea to 10X Genomics' use of HDF5 to store a column-sparse compressed matrix, currently implemented with the `TENxMatrix` backend. This reads in the relevant indices and values on request, rather than loading everything in at once. The difficulty is that fast random access requires custom code, because we can no longer take advantage of the HDF5 library's facilities for dense matrices.

**Comment by hpages** [comment]
@phaverty If you don't mind loosing the RLE representation, you could just use `saveHDF5SummarizedExperiment()`. This will save all your assays in a single HDF5 file (with 1 dataset per assay). Your RleMatrix assays will end up being stored as regular (i.e. dense) HDF5 datasets (after being de-RLEfied block by block on the fly) so you might end up with a very big HDF5 file. Have you tried it? Maybe you did but ran into some performance issues? You might want to experiment a little bit with  different chunk geometries and compression levels (these, and other settings, can be controlled via the `saveHDF5SummarizedExperiment()` and `writeHDF5Array()` interfaces).

If you do care about keeping the RLE representation then we would need a specific backend for that (and I've been thinking a lot about how this could be done). It's possible to store RLE representations in HDF5, in the same fashion than what the 10x Genomics people have done with their "HDF5-based sparse matrix representation", but, as @LTLA said, this is far from being a satisfying solution. One of the major problems is that HDF5 doesn't natively support this so it would require a specific organization of the data as well as an extra layer of logic and code to deal with this data. Another problem is that this specific organization of the data is unlikely to allow fast random access. But maybe you don't need that because your RLE data fits entirely in memory so it could just be loaded back and then fast random access woudn't really matter anymore.

**Comment by phaverty** [comment]
I'm most interested in reading and writing the whole RLEMatrix at once. I think they are small enough that doing so should be fine. I wouldn't be so sad about storing it as a dense matrix and compressing it to an RLEMatrix at read time. Usually these RLEMatrix objects have some sister matrices that are dense anyway, so the disk space is not a problem. Perhaps we could get by with a subclass of RleMatrix that knows the path to a dense HDF5 file and reads and compresses the matrix the first time it is accessed?

I like the idea of having a collection of matrices stored with the same file format / technology, especially one that is accessible from multiple languages. My standby has been to serialize SummarizedExperiments that contain some of my old genoset::RleDataFrame objects and some bigMemoryExtras::BigMatrix objects, but I'm hoping to allow my non-R friends to play too.

BTW, RleMatrix is awesome. I somehow missed hearing about that until just recently. Time to go deprecate RleDataFrame :-)

**Comment by lawremi** [comment]
Does the 10X representation have cross-language support? Might it emerge as some sort of standard?

**Comment by lawremi** [comment]
I think it's worth considering implementing the custom code for fast random access and actually storing the compressed representation. For example, store the run-ends and perform a binary search. It would be interesting to see how much Rle or some other sparse encoding saves relative to the built-in HDF5 compression, which definitely slows down column-wise restriction in our tests.

**Comment by phaverty** [comment]
Thanks @hpages ! The Re-RLE-ing trick works for me for now.

**Comment by hpages** [comment]
Closing this.

@phaverty: feel free to re-open if you want to further discuss this. Thanks!
