### ISSUE TITLE
1.7.6 build error

### ISSUE THREAD

**Issue by pati-ni** [Bioconductor/HDF5Array#5]
While trying to install HDF5Array I get this error:
```
Error in setMethod("path", "HDF5ArraySeed", function(object) object@filepath) : 
  no existing definition for function ‘path’

```
Should be noted that I got a very similar error with `DelayedArray` as well which was solved by installing the older version of `DelayedArray` 0.5.13 from the project's github repo

**Comment by hpages** [comment]
The `path()` generic was added to BiocGenerics 0.25.1. I added this requirements to the DESCRIPTION file: https://github.com/Bioconductor/HDF5Array/commit/efd4fc41437d9d446a9fd2e67e19d3a3068966cd

HDF5Array is a Bioconductor package so please make sure to always install Bioconductor packages with `biocLite()`. See https://bioconductor.org/install/
This will take care of keeping all your packages in sync (update them from times to times by calling `biocLite()` with no arguments). In particular avoid installing from GitHub as it will almost always lead to some packages not being in sync.  Since HDF5Array 1.7.6 belongs to Bioconductor devel, you'll need the current R devel (R 3.5).

**Comment by pati-ni** [comment]
I see, so please update R dependency to 3.5. Thanks
