### ISSUE TITLE
Problem installing HDF5Array on R 4.3.0

### ISSUE THREAD

**Issue by AndreaRP** [Bioconductor/HDF5Array#53]
Hi,

I just upgraded my base R to v4.3 (under Ubuntu 22.04.2 LTS) and now I can't install HDF5Array. The errors I get are the following:
ERROR: compilation failed for package ‘rhdf5filters’
ERROR: dependency ‘rhdf5filters’ is not available for package ‘rhdf5’
ERROR: dependencies ‘rhdf5’, ‘rhdf5filters’ are not available for package ‘HDF5Array’

I've tried installing rhdf5filters separately, both through Bioconductor and GitHub via devtools, but I always get compilation errors. Is there any way to solve this issue?
Thanks

**Comment by lshep** [comment]
It would help to show your installation command and the output showing the error.

**Comment by hpages** [comment]
Also:
- It seems to be a **rhdf5filters** issue rather than a **HDF5Array** issue. Please report to the **rhdf5filters** maintainer. 
- However please note that the Bioconductor support site is usually preferred for this type of question: https://support.bioconductor.org (when you ask there, make sure to show the command you used for installation as well as the _full_ output produced by the command, as Lori suggested).

Thanks
